# Generated by Django 5.2 on 2025-04-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_patientregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientregistration',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patientregistration',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
